Make it possilbe to remove articles from group
duvholt/frontier pull request #4
Opened 2016-10-01 10:50 UTC by tu55eladd

2016-10-01 10:55 UTC, tu55eladd commented
Branch is based add-article branch and might seem big but is really just last four commits.

2016-10-01 10:57 UTC, duvholt commented
Should we close the other pull request and do review on this one instead? Or finish review on the other pr and then this?

2016-10-01 11:00 UTC, tu55eladd commented
Think the other one should be merged first, then this one. Hopefully "duplicated commits" will disappear when the other one is merged.

2016-10-01 11:26 UTC, duvholt requested changes

2016-10-01 11:26 UTC, duvholt commented on src/reducers/articleGroups.js
> +        default:
Accident indent I guess?

2016-10-01 11:26 UTC, duvholt commented on src/reducers/articleGroups.js
> +      state[groupId].articles.splice(articleIndex, 1);
This is mutating the articles list. Meaning that the previous state is also changed.

Use the `removeFromArticles` helper function.
Also I think it's cleaner to do this in the subreducer I made. Call it like `ADD_ARTICLE_TO_GROUP` does.

2016-10-01 15:23 UTC, tu55eladd commented
Should be good now

2016-10-06 13:13 UTC, duvholt approved these changes

2016-10-06 13:13 UTC, merged